project/server/main/forms.py
# project/server/main/forms.py


from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired


class UploadForm(FlaskForm):
    file1 = FileField('inputFile1',
        validators=[
            FileRequired(),
            FileAllowed(['csv', 'CSV only!'])
        ])
    file2 = FileField('inputFile2',
        validators=[
            FileRequired(),
            FileAllowed(['csv', 'CSV only!'])
        ])

project/__init__.py
# project/__init__.py

project/server/__init__.py
# project/server/__init__.py


import os

from flask import Flask, render_template
from flask_bootstrap import Bootstrap


# instantiate the extensions
bootstrap = Bootstrap()


def create_app(script_info=None):

    # instantiate the app
    app = Flask(
        __name__,
        template_folder="../client/templates",
        static_folder="../client/static",
    )

    # set config
    app_settings = os.getenv(
        "APP_SETTINGS", "project.server.config.ProductionConfig"
    )
    app.config.from_object(app_settings)

    # set up extensions
    bootstrap.init_app(app)

    # register blueprints
    from project.server.main.views import main_blueprint

    app.register_blueprint(main_blueprint)

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    # shell context for flask cli
    @app.shell_context_processor
    def ctx():
        return {"app": app}

    return app

project/server/main/__init__.py
# project/server/main/__init__.py

project/server/main/views.py
# project/server/main/views.py


from flask import render_template, Blueprint, flash, redirect, url_for, request, current_app
from project.server.main.helpers import CompareTwoDict, ConvertCSVtoDict, wrapper, SuggestPossibilities
from project.server.main.forms import UploadForm
from threading import Thread
from queue import Queue

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def home():
    """
    Render the home page with upload form
    """

    uploadform = UploadForm()
    return render_template("main/home.html", uploadform=uploadform)


@main_blueprint.route('/upload', methods=['POST'])
def upload():
    """
    /upload [POST]
    a function to handle file uploads of 2 csvs
    the function would compare the 2 csvs and return the result
    it will redirect to home with the result  
    """
    uploadform = UploadForm()
    if uploadform.validate_on_submit():
        # convert csv to dict
        q1, q2 = Queue(), Queue()
        Thread(target=wrapper, args=(ConvertCSVtoDict, uploadform.file1.data, q1)).start() 
        Thread(target=wrapper, args=(ConvertCSVtoDict, uploadform.file2.data, q2)).start()
        dict1, dict2 = q1.get(), q2.get()

        # validation if the header of two files is not the same
        if dict1["header"] != dict2["header"]:
            flash("The two files do not have the same header")
            return redirect(url_for('main.home'))
        # compare two dict
        dict_report1 = CompareTwoDict(dict1, dict2)
        dict_report2 = CompareTwoDict(dict2, dict1)
        if "errors" in dict_report1 and (dict_report1["errors"] != None or dict_report2["errors"] != None):
            flash("File is not compatible with the application")
            return redirect(url_for('main.home'))
        dict_report1, dict_report2 = SuggestPossibilities(dict_report1, dict_report2, dict1["header"])
        
        return render_template("main/home.html", uploadform=uploadform, dict_report={
            "data":[
                {
                    "filename": uploadform.file1.data.filename,
                    "dict_report": dict_report1,
                    "total_data": dict1["total_data"],
                    "header": dict1["header"],
                    "duplicate_data": dict1["duplicate_data"],
                }, {
                    "filename": uploadform.file2.data.filename,
                    "dict_report": dict_report2,
                    "total_data": dict2["total_data"],
                    "header": dict2["header"],
                    "duplicate_data": dict2["duplicate_data"],
                }
            ]
        })
    
    flash("file is invalid, kindly check the file again")
    return redirect(url_for('main.home'))

project/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>{{ config.APP_NAME }}{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/client/templates/footer.html
<footer>
  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <small>
        <span>©
          <a href="http://github.com/nmmugia">Mugia N M</a>
        </span>
      </small>
    </div>
  </nav>
</footer>

project/client/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

project/client/templates/main/home.html
{% extends "_base.html" %}
{% block content %}
{% import "bootstrap/wtf.html" as wtf %}

  <div class="border round p-5">
    <div class="form-group">
      <h3>Specify files to compare!</h3>
    </div>
    <form class="form" role="form" method="post" action="{{ url_for('main.upload') }}" enctype="multipart/form-data">
      
      {{ uploadform.csrf_token }}
      {{ uploadform.hidden_tag() }}
      {{ wtf.form_errors(uploadform, hiddens="only") }}

      <div class="form-group">
        <label for="inputFile1" class="col-sm-2 control-label">Select file 1</label>
        {{ uploadform.file1(class_="form-control") }}
      </div>

      <div class="form-group">
        <label for="inputFile2" class="col-sm-2 control-label">Select file 2</label>
        {{ uploadform.file2(class_="form-control") }}
      </div>

      <button type="submit" class="btn btn-default">Compare</button>
    </form>
  </div>
  
  {% if dict_report is defined %}
  <div class="row m-5 border round p-5">
    <div class="row col-md-12">
      <h3>Comparison result</h3>
      <hr><br>
    </div>
    <div class="row col-md-12">
      <div class="row col-md-12 m-2">
        <div class="col-md-6">
          <table class="table-comparison" >
            <tr>
              <th>{{ dict_report.data[0].filename }}</th>
            </tr>
            <tr>
              <td>Total Records:</td><td>{{ dict_report.data[0].total_data }}</td>
            </tr>
            <tr>
              <td>Matching Records:</td><td>{{ dict_report.data[0].dict_report.matching_records }}</td>
            </tr>
            <tr>
              <td>Unmatched Records:</td><td>{{ dict_report.data[0].dict_report.unmatched_records }}</td>
            </tr>
        </table>   
        </div>
        <div class="col-md-6">
          <table class="table-comparison" >
            <tr>
              <th>{{ dict_report.data[1].filename }}</th>
            </tr>
            <tr>
              <td>Total Records:</td><td>{{ dict_report.data[1].total_data }} {% if dict_report.data[1].duplicate_data > 0 %}(Duplicate: {{dict_report.data[1].duplicate_data}}){% endif %}</td>
            </tr>
            <tr>
              <td>Matching Records:</td><td>{{ dict_report.data[1].dict_report.matching_records }}</td>
            </tr>
            <tr>
              <td>Unmatched Records:</td><td>{{ dict_report.data[1].dict_report.unmatched_records }}</td>
            </tr>
        </table>   
        </div>
      </div>
      <div class="row col-md-12 m-2">
        <button class="btn btn-default" id="unmatchedReportBTN">Unmatched Report</button>
      </div>
    </div>
  </div>

  <div class="row d-none m-5 border round p-5" id="unmatchedReport">
    <div class="row col-md-12">
    <div class="col-md-6">
      <h3>Unmatched report</h3>
    </div>
    </div>
    <div class="row col-md-12">
    <div class="col-md-6">
      <table class="table table-responsive">
        {% for header_item in dict_report.data[0].header %}
          <th>{{ header_item }}</th>
        {% endfor %}
      </tr>
      {% for value in dict_report.data[0].dict_report.unmatched_data %}
        {%if dict_report.data[0].dict_report.unmatched_data[value]["points"] > 0 %}
              <tr class="bg-success">
            {% else %}
              <tr>
            {% endif %}
            {% for value_key in dict_report.data[0].header %}
                {% if value_key != 'total_exist' %}
                  <td>{{ dict_report.data[0].dict_report.unmatched_data[value][value_key] }}</td>
                {% endif %}
          {% endfor %}
        </tr>
      {% endfor %}
    </table>
    </div>

    <div class="col-md-6">
      <table class="table  table-responsive">
        {% for header_item in dict_report.data[1].header %}
          <th>{{ header_item }}</th>
        {% endfor %}
      </tr>
      {% for value in dict_report.data[1].dict_report.unmatched_data %}
        {%if dict_report.data[1].dict_report.unmatched_data[value]["points"] > 0 %}
          <tr class="bg-success">
        {% else %}
          <tr>
        {% endif %}
            {% for value_key in dict_report.data[1].header %}
                {% if value_key != 'total_exist' %}
                  <td>{{ dict_report.data[1].dict_report.unmatched_data[value][value_key] }}</td>
                {% endif %}
            {% endfor %}
        </tr>
      {% endfor %}
      </table>
    </div>
    </div>
    <div class="row col-md-12">
      <span>*the table is draggable horizontally if the column is overflow</span>
      <span>*<svg width="20" height="20">
        <rect width="20" height="20" style="fill:#28a745;stroke-width:3;stroke:rgb(0,0,0)" />
        </svg> means that there is a possible match, but the data is not perferctly matched</span>
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}